package basedatos;

import basedatos.exceptions.*;
import basedatos.modelo.*;

import java.beans.PropertyVetoException;
import java.io.IOException;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.math.BigInteger;

public class PruebaJulia {

    public static void main(String[] args) throws ExceptionCampoInexistente, ExceptionCampoInvalido, PropertyVetoException, SQLException, IOException {

		StatsUsuarioVO prueba = InterfazDatos.instancia().obtenerTodasStatsUsuario("zquerol");

		System.out.println("Ganadas: " + prueba.getGanadas() + " Perdidas: " + prueba.getPerdidas() + " Abandonadas: " + prueba.getAbandonaste() + " Te abandonaron: " + prueba.getTeAbandonaron());
	
//		SesionVO s = new SesionVO("zcarrera", "www.nadasoloesunaprueba.com");
//		InterfazDatos.instancia().crearSesionAbierta(s);
//		
//		String url = InterfazDatos.instancia().obtenerUrlSesion("zcarrera");
//		System.out.println("Primera url: " + url);

//		url = InterfazDatos.instancia().obtenerUrlSesion("viniesta");
//		System.out.println("Segunda url: " + url);

//		url = InterfazDatos.instancia().obtenerUrlSesion("juliagviu");
//		System.out.println("Tercera url: " + url);

//		InterfazDatos.instancia().crearSesionAbierta(s);

//		Timestamp ts = java.sql.Timestamp.valueOf("2018-02-23 10:54:09.0");
//        TorneoVO t = new TorneoVO("torneo2", "descripcion1", ts, true, 3, 2, 1);

//		Timestamp ts2 = java.sql.Timestamp.valueOf("2018-02-23 10:54:09.0");
//		TorneoVO t2 = new TorneoVO("torneoVacio", "descripcion1", ts2, true, 3, 2, 1);
//		t2.setId(BigInteger.valueOf(7));

//		UsuarioVO u1 = InterfazDatos.instancia().obtenerDatosUsuario("zcarrera");
//		UsuarioVO u2 = InterfazDatos.instancia().obtenerDatosUsuario("yolanda86");
//		UsuarioVO u3 = InterfazDatos.instancia().obtenerDatosUsuario("viniesta");
//		UsuarioVO u4 = InterfazDatos.instancia().obtenerDatosUsuario("somozablanca");
//		UsuarioVO u5 = InterfazDatos.instancia().obtenerDatosUsuario("rosario31");
//		UsuarioVO u6 = InterfazDatos.instancia().obtenerDatosUsuario("nplanas");
//		UsuarioVO u7 = InterfazDatos.instancia().obtenerDatosUsuario("inmaculada13");
//		UsuarioVO u8 = InterfazDatos.instancia().obtenerDatosUsuario("godoydiego");
//		UsuarioVO u9 = InterfazDatos.instancia().obtenerDatosUsuario("carmen90");

		//InterfazDatos.instancia().crearTorneo(t);
		//InterfazDatos.instancia().crearTorneo(t2);

//		t.setDescripcion("una descripcion cambiada");
//		t.setNumFases(8);
//		t.setPremioPuntuacionPrimera(8);

//		InterfazDatos.instancia().modificarTorneo(t);
//		
//		TorneoVO t2 = InterfazDatos.instancia().obtenerDatosTorneo(t.getId());
//		System.out.println("torneo " + t2.getNombre() + " desc: " + t2.getDescripcion() + "timeInicio: " + t2.getTimeInicio() + "numFases: " + t2.getNumFases() + "premiopunt: " + t2.getPremioPuntuacionPrimera() + "premiodiv: "+ t2.getPremioDivisaPrimera());

//		InterfazDatos.instancia().eliminarTorneo(t2.getId());

//		InterfazDatos.instancia().apuntarTorneo(u1,t2);
//		InterfazDatos.instancia().apuntarTorneo(u2,t2);
//		InterfazDatos.instancia().apuntarTorneo(u3,t2);
//		InterfazDatos.instancia().apuntarTorneo(u4,t2);
//		InterfazDatos.instancia().apuntarTorneo(u5,t2);
//		InterfazDatos.instancia().apuntarTorneo(u6,t2);
//		InterfazDatos.instancia().apuntarTorneo(u7,t2);
//		InterfazDatos.instancia().apuntarTorneo(u8,t2);

//		InterfazDatos.instancia().abandonarTorneo(u6,t2);

//		InterfazDatos.instancia().apuntarTorneo(u8,t2);
//		InterfazDatos.instancia().apuntarTorneo(u9,t2);

//		ArrayList<TorneoVO> resultadoguay = InterfazDatos.instancia().obtenerTorneosProgramados();
//		for(int i = 0; i<resultadoguay.size(); i++){
//			System.out.println(resultadoguay.get(i).getNombre() + resultadoguay.get(i).getDescripcion());
//		}

//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(2, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("carmen90"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("lvalenzuela"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('A');
//p.setPuntos1(35);
//p.setPuntos2(64);
//p.setAbandonador(1);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(4, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("nicolasfont"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("manuela28"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("zamorajose-fran"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("josefinalosada"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('1');
//p.setPuntos1(101);
//p.setPuntos2(29);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(4, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("raquel65"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("vicenta65"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("alba05"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("blanca18"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('1');
//p.setPuntos1(101);
//p.setPuntos2(84);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(2, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("carmen98"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("albertolago"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('2');
//p.setPuntos1(11);
//p.setPuntos2(101);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(4, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("jose-angelbenit"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("vurrutia"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("alba05"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("jose-antonio59"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('1');
//p.setPuntos1(101);
//p.setPuntos2(57);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(2, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("tmas"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("calatayudjuan-f"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('A');
//p.setPuntos1(87);
//p.setPuntos2(11);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(2, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("ihidalgo"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("xbriones"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('1');
//p.setPuntos1(101);
//p.setPuntos2(21);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(2, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("purificacion66"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("qmoliner"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('2');
//p.setPuntos1(6);
//p.setPuntos2(101);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(4, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("josefina16"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("jarino"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("domingo01"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("rodrigo59"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('2');
//p.setPuntos1(51);
//p.setPuntos2(101);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(2, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("igarriga"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("xroyo"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('1');
//p.setPuntos1(101);
//p.setPuntos2(45);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(2, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("emilionaranjo"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("beldasoledad"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('A');
//p.setPuntos1(83);
//p.setPuntos2(31);
//p.setAbandonador(1);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(4, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("fvendrell"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("galianosilvia"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("luisa27"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("shoyos"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('2');
//p.setPuntos1(92);
//p.setPuntos2(101);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(2, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("ymoliner"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("belen82"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('A');
//p.setPuntos1(73);
//p.setPuntos2(70);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(4, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("remediossoria"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("sguillen"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("ehernando"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("ycastello"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('1');
//p.setPuntos1(101);
//p.setPuntos2(27);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(2, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("umarti"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("carrerasvirgini"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('1');
//p.setPuntos1(101);
//p.setPuntos2(40);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(4, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("vcabeza"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("vcoloma"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("buribe"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("vicente00"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('1');
//p.setPuntos1(101);
//p.setPuntos2(65);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(2, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("teresa92"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("acastellanos"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('1');
//p.setPuntos1(101);
//p.setPuntos2(2);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(4, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("vcabeza"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("perezfernando"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("milagrosfiguero"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("belensolera"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('2');
//p.setPuntos1(34);
//p.setPuntos2(101);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(2, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("jose-antoniopin"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("roldanjosep"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('2');
//p.setPuntos1(24);
//p.setPuntos2(101);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(4, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("carriondaniela"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("victor-manuel59"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("lourdes30"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("egisbert"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('A');
//p.setPuntos1(79);
//p.setPuntos2(13);
//p.setAbandonador(3);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(2, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("alvaro92"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("samuelnavarrete"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('A');
//p.setPuntos1(27);
//p.setPuntos2(66);
//p.setAbandonador(1);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(4, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("novoajosefina"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("purificacion92"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("alicia06"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("xbriones"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('1');
//p.setPuntos1(101);
//p.setPuntos2(7);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(2, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("samuelnavarrete"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("diego84"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('1');
//p.setPuntos1(101);
//p.setPuntos2(10);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(4, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("clarainiesta"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("marruano"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("jose-angelbenit"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("alexmarquez"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('1');
//p.setPuntos1(101);
//p.setPuntos2(9);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(2, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("alba05"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("gordillobeatriz"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('1');
//p.setPuntos1(101);
//p.setPuntos2(79);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(2, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("pilaracuna"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("josefina68"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('1');
//p.setPuntos1(101);
//p.setPuntos2(27);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(2, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("angelesayuso"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("alfredocalvo"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('1');
//p.setPuntos1(101);
//p.setPuntos2(12);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(4, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("xavier32"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("lopezmariano"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("estherreina"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("raquel65"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('1');
//p.setPuntos1(101);
//p.setPuntos2(61);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(2, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("duranluis-migue"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("sonia61"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('A');
//p.setPuntos1(61);
//p.setPuntos2(40);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(2, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("raquel65"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("dalmazan"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('2');
//p.setPuntos1(47);
//p.setPuntos2(101);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(4, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("duranluis-migue"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("mancebomaria"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("consuelomartine"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("cerdamagdalena"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('2');
//p.setPuntos1(56);
//p.setPuntos2(101);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(2, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("zquerol"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("adadiamagdalena"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('1');
//p.setPuntos1(101);
//p.setPuntos2(73);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(2, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("earce"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("ymoliner"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('2');
//p.setPuntos1(42);
//p.setPuntos2(101);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(4, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("evaserra"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("silviagonzalez"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("felipe01"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("victor-manueldu"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('1');
//p.setPuntos1(101);
//p.setPuntos2(8);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(4, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("alejandraocana"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("fiolfatima"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("joancasanovas"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("andresjose-fran"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('1');
//p.setPuntos1(101);
//p.setPuntos2(26);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(2, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("jsuarez"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("gmiguel"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('1');
//p.setPuntos1(101);
//p.setPuntos2(36);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(2, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("ismael48"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("requenaines"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('1');
//p.setPuntos1(101);
//p.setPuntos2(36);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(4, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("gilagustin"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("gargallofelix"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("margaritavaldes"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("belen82"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('2');
//p.setPuntos1(10);
//p.setPuntos2(101);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(2, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("mariagamez"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("sebastiantormo"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('2');
//p.setPuntos1(77);
//p.setPuntos2(101);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(2, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("acasares"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("solanovicenta"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('2');
//p.setPuntos1(14);
//p.setPuntos2(101);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(4, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("ncoloma"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("enrique31"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("novoajosefina"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("otalavera"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('A');
//p.setPuntos1(7);
//p.setPuntos2(12);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(2, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("ariasruben"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("cepedaamparo"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('A');
//p.setPuntos1(17);
//p.setPuntos2(11);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(4, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("silviagonzalez"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("manuelmohamed"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("lourdes30"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("mmorata"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('1');
//p.setPuntos1(101);
//p.setPuntos2(78);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(4, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("wduran"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("kroura"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("laviles"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("smarcos"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('2');
//p.setPuntos1(10);
//p.setPuntos2(101);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(4, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("clarainiesta"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("daniela67"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("antonjuana"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("alicia11"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('1');
//p.setPuntos1(101);
//p.setPuntos2(25);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(4, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("asuncion41"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("folchpilar"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("margarita19"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("remedios76"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('1');
//p.setPuntos1(101);
//p.setPuntos2(27);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(2, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("alicia11"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("javierboix"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('1');
//p.setPuntos1(101);
//p.setPuntos2(82);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(2, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("joaquinroman"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("juliaguitart"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('2');
//p.setPuntos1(67);
//p.setPuntos2(101);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(2, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("egisbert"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("ismael48"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('1');
//p.setPuntos1(101);
//p.setPuntos2(60);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(2, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("herreronuria"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("martinpastor"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('2');
//p.setPuntos1(51);
//p.setPuntos2(101);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(2, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("ycastello"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("cepedaamparo"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('2');
//p.setPuntos1(31);
//p.setPuntos2(101);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(2, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("victoria55"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("lorena77"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('2');
//p.setPuntos1(39);
//p.setPuntos2(101);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(2, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("evaserra"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("tmas"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('2');
//p.setPuntos1(32);
//p.setPuntos2(101);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(4, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("calatayudjuan-f"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("rosario36"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("beatrizborrell"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("arribasmiguel"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('2');
//p.setPuntos1(57);
//p.setPuntos2(101);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(2, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("lidia62"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("epages"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('A');
//p.setPuntos1(49);
//p.setPuntos2(96);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(4, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("cepedaamparo"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("igarriga"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("fatima09"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("jesusberrocal"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('2');
//p.setPuntos1(90);
//p.setPuntos2(101);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(2, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("victor-manueldu"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("smateo"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('1');
//p.setPuntos1(101);
//p.setPuntos2(5);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(4, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("juanbosch"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("lopezmariano"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("marruano"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("lamaya"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('1');
//p.setPuntos1(101);
//p.setPuntos2(92);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(4, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("rosario31"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("blancaacedo"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("felix76"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("kexposito"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('1');
//p.setPuntos1(101);
//p.setPuntos2(29);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(4, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("marruano"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("yolanda11"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("asuncion41"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("ismael10"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('1');
//p.setPuntos1(101);
//p.setPuntos2(85);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(4, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("pintomaria"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("ygallardo"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("arranzpedro"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("alexmarquez"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('2');
//p.setPuntos1(38);
//p.setPuntos2(101);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(4, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("enrique31"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("josepleal"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("dcriado"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("xbriones"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('2');
//p.setPuntos1(39);
//p.setPuntos2(101);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(4, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("emiliacollado"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("josefinalosada"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("icarbajo"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("uriaruben"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('1');
//p.setPuntos1(101);
//p.setPuntos2(6);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(4, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("hmaza"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("xavier32"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("lamaya"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("consuelomartine"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('2');
//p.setPuntos1(71);
//p.setPuntos2(101);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(2, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("ramon73"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("salvadorconesa"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('1');
//p.setPuntos1(101);
//p.setPuntos2(57);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(2, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("yolanda86"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("felipe03"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('1');
//p.setPuntos1(101);
//p.setPuntos2(99);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(4, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("zamorajose-fran"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("imugica"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("trinidadvillega"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("cuadradohector"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('1');
//p.setPuntos1(101);
//p.setPuntos2(6);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(4, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("alexcolom"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("mmorata"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("mdalmau"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("cristian06"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('1');
//p.setPuntos1(101);
//p.setPuntos2(17);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(2, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("gvega"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("kterron"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('2');
//p.setPuntos1(39);
//p.setPuntos2(101);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(2, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("ygallardo"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("echevarriagonza"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('A');
//p.setPuntos1(86);
//p.setPuntos2(98);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(4, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("zquerol"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("victor-manuel59"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("lorenavendrell"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("alexmarquez"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('2');
//p.setPuntos1(73);
//p.setPuntos2(101);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(2, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("claudianieto"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("fatimaramos"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('1');
//p.setPuntos1(101);
//p.setPuntos2(77);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(4, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("ocollado"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("codinadolores"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("xavierdomingo"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("zquerol"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('1');
//p.setPuntos1(101);
//p.setPuntos2(4);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(4, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("fmoles"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("cuadradosalvado"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("vmascaro"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("tomascasares"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('A');
//p.setPuntos1(52);
//p.setPuntos2(47);
//p.setAbandonador(2);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(2, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("nsaura"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("cmayol"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('1');
//p.setPuntos1(101);
//p.setPuntos2(54);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(4, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("marina82"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("barberaeva"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("raquelreguera"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("pipilar"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('A');
//p.setPuntos1(81);
//p.setPuntos2(94);
//p.setAbandonador(2);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(2, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("david74"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("clarainiesta"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('2');
//p.setPuntos1(55);
//p.setPuntos2(101);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(2, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("alfredocalvo"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("patricia56"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('1');
//p.setPuntos1(101);
//p.setPuntos2(46);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(4, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("remedios41"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("vurrutia"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("patricia56"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("qbou"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('2');
//p.setPuntos1(37);
//p.setPuntos2(101);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(4, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("alejandrolucas"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("jose-miguel49"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("vicentaribera"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("luzrosado"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('2');
//p.setPuntos1(56);
//p.setPuntos2(101);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(4, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("kvalverde"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("mohamedmarin"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("vicentaribera"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("andreatormo"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('1');
//p.setPuntos1(101);
//p.setPuntos2(50);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(4, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("paulaantunez"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("umacias"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("felixagudo"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("jose-angel08"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('2');
//p.setPuntos1(34);
//p.setPuntos2(101);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(4, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("david74"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("diazsantiago"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("angelaarias"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("usobrino"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('1');
//p.setPuntos1(101);
//p.setPuntos2(72);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(2, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("jose-luisayllon"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("mario07"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('1');
//p.setPuntos1(101);
//p.setPuntos2(43);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(2, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("remedios41"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("ana16"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('2');
//p.setPuntos1(59);
//p.setPuntos2(101);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(2, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("alicia11"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("duranluis-migue"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('1');
//p.setPuntos1(101);
//p.setPuntos2(58);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(4, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("cristinamateo"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("amparo27"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("igarriga"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("marquezsilvia"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('2');
//p.setPuntos1(48);
//p.setPuntos2(101);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(2, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("imugica"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("suarezjose"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('1');
//p.setPuntos1(101);
//p.setPuntos2(82);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(4, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("emilionaranjo"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("vamigo"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("alejandra88"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("andrea68"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('1');
//p.setPuntos1(101);
//p.setPuntos2(21);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(4, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("catalinasosa"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("javier73"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("marinagirona"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("cerdamagdalena"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('1');
//p.setPuntos1(101);
//p.setPuntos2(8);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(4, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("martin92"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("julian15"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("felix76"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("albert04"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('2');
//p.setPuntos1(6);
//p.setPuntos2(101);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(2, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("lorenavendrell"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("estherreina"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('2');
//p.setPuntos1(91);
//p.setPuntos2(101);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(2, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("jose-carlosseco"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("carolinadonaire"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('1');
//p.setPuntos1(101);
//p.setPuntos2(56);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(4, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("angelesayuso"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("kariza"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("albertopareja"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("cpelayo"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('1');
//p.setPuntos1(101);
//p.setPuntos2(93);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(4, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("lvalenzuela"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("zcarrera"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("cmarin"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("cristinamateo"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('1');
//p.setPuntos1(101);
//p.setPuntos2(80);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(4, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("cpelayo"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("herreronuria"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("carriondaniela"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("diazsantiago"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('A');
//p.setPuntos1(7);
//p.setPuntos2(42);
//p.setAbandonador(1);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(2, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("victor-manuel59"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("tapiafrancisca"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('2');
//p.setPuntos1(49);
//p.setPuntos2(101);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(2, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("emilio78"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("aranafrancisco-"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('1');
//p.setPuntos1(101);
//p.setPuntos2(16);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(4, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("lvalenzuela"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("ycastello"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("fmoles"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("umarti"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('2');
//p.setPuntos1(66);
//p.setPuntos2(101);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);
//a = new ArrayList<>();
//v = new ArrayList<>(Collections.nCopies(4, 0));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("calatayudjuan-f"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("mirallesalfredo"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("sbas"));
//a.add(InterfazDatos.instancia().obtenerDatosUsuario("tmas"));
//p = new PartidaVO(true, a);
//InterfazDatos.instancia().crearNuevaPartida(p);
//p.setCuarentas(v);
//p.setVeintes(v);
//p.setTimeFin(new Timestamp(System.currentTimeMillis()));
//p.setGanador('2');
//p.setPuntos1(86);
//p.setPuntos2(101);
//p.setAbandonador(0);
//InterfazDatos.instancia().finalizarPartida(p);



    }
}


